//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transaction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub from_account_id: Option<Uuid>,
    pub to_account_id: Option<Uuid>,
    pub txn_type: String,
    #[sea_orm(column_type = "Decimal(Some((18, 4)))")]
    pub amount: Decimal,
    pub currency_code: String,
    #[sea_orm(column_type = "Decimal(Some((18, 4)))")]
    pub to_amount: Option<Decimal>,
    pub to_currency_code: Option<String>,
    pub category: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub note: Option<String>,
    pub occurred_at: DateTimeWithTimeZone,
    pub ref_transaction_id: Option<Uuid>,
    pub merchant: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::FromAccountId",
        to = "super::account::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Account2,
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::ToAccountId",
        to = "super::account::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Account1,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::RefTransactionId",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
